# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/p5220/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/p52xx/p5220/system/lib/hw/hwcomposer.santos10lte.so:system/lib/hw/hwcomposer.santos10lte.so \
    vendor/samsung/p52xx/p5220/system/bin/gpsd:system/bin/gpsd \
    vendor/samsung/p52xx/p5220/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/p52xx/p5220/system/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/p52xx/p5220/system/lib/hw/camera.santos10lte.so:system/lib/hw/camera.vendor.santos10lte.so \
    vendor/samsung/p52xx/p5220/sbin/cbd:root/sbin/cbd \
    vendor/samsung/p52xx/p5220/system/lib/libsec-ril.so:system/lib/libsec-ril.so
