# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/p5210/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/p52xx/common/system/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/samsung/p52xx/common/system/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/samsung/p52xx/common/system/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/samsung/p52xx/common/system/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/samsung/p52xx/common/system/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/samsung/p52xx/common/system/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/samsung/p52xx/common/system/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/p52xx/common/system/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/samsung/p52xx/common/system/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/samsung/p52xx/common/system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so:system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so \
    vendor/samsung/p52xx/common/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so \
    vendor/samsung/p52xx/common/system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so \
    vendor/samsung/p52xx/common/system/vendor/lib/hw/gralloc.clovertrail.so:system/vendor/lib/hw/gralloc.clovertrail.so \
    vendor/samsung/p52xx/common/system/lib/libcorkscrew.so:system/lib/libcorkscrew.so \
    vendor/samsung/p52xx/common/system/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/samsung/p52xx/common/system/lib/libsepdrm.so:system/lib/libsepdrm.so \
    vendor/samsung/p52xx/common/system/lib/libmultidisplay.so:system/lib/libmultidisplay.so \
    vendor/samsung/p52xx/common/system/lib/libmultidisplayjni.so:system/lib/libmultidisplayjni.so \
    vendor/samsung/p52xx/common/system/lib/libmixvbp.so:system/lib/libmixvbp.so \
    vendor/samsung/p52xx/common/system/lib/libmixvbp_h264.so:system/lib/libmixvbp_h264.so \
    vendor/samsung/p52xx/common/system/lib/libmixvbp_mpeg4.so:system/lib/libmixvbp_mpeg4.so \
    vendor/samsung/p52xx/common/system/lib/libmixvbp_vc1.so:system/lib/libmixvbp_vc1.so \
    vendor/samsung/p52xx/common/system/lib/pvr_drv_video.so:system/lib/pvr_drv_video.so \
    vendor/samsung/p52xx/common/system/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/p52xx/common/system/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/p52xx/common/system/bin/orientationd:system/bin/orientationd \
    vendor/samsung/p52xx/common/system/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/samsung/p52xx/common/system/bin/cpdd:system/bin/cpdd \
    vendor/samsung/p52xx/common/system/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/p52xx/common/system/lib/libia_aiq.so:system/lib/libia_aiq.so \
    vendor/samsung/p52xx/common/system/lib/libia_aiq_cp.so:system/lib/libia_aiq_cp.so \
    vendor/samsung/p52xx/common/system/lib/libia_mkn.so:system/lib/libia_mkn.so \
    vendor/samsung/p52xx/common/system/lib/libia_nvm.so:system/lib/libia_nvm.so \
    vendor/samsung/p52xx/common/system/lib/libmfldadvci.so:system/lib/libmfldadvci.so \
    vendor/samsung/p52xx/common/system/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/p52xx/common/system/lib/libtbd.so:system/lib/libtbd.so \
    vendor/samsung/p52xx/common/system/vendor/lib/hw/memtrack.clovertrail.so:system/vendor/lib/hw/memtrack.clovertrail.so \
    vendor/samsung/p52xx/common/system/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/p52xx/common/system/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/p52xx/common/system/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/p52xx/common/system/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/p52xx/common/system/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd \
    vendor/samsung/p52xx/common/system/vendor/firmware/bcm4334_murata.hcd:system/vendor/firmware/bcm4334_murata.hcd \
    vendor/samsung/p52xx/common/system/vendor/firmware/bcm4334_semco.hcd:system/vendor/firmware/bcm4334_semco.hcd \
    vendor/samsung/p52xx/common/system/etc/firmware/shisp_css15.bin:system/etc/firmware/shisp_css15.bin \
    vendor/samsung/p52xx/common/system/etc/firmware/isp_fr.bin:system/etc/firmware/isp_fr.bin \
    vendor/samsung/p52xx/common/system/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/p52xx/common/system/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/p52xx/common/system/etc/firmware/fw_sst_08e7.bin:system/etc/firmware/fw_sst_08e7.bin
